apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-telegram-bot-pvc
  namespace: argocd
  labels:
    app: argocd-telegram-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
