apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-telegram-bot
  namespace: argocd
  labels:
    app: argocd-telegram-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-telegram-bot-reader
  labels:
    app: argocd-telegram-bot
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-telegram-bot-reader-binding
  labels:
    app: argocd-telegram-bot
subjects:
  - kind: ServiceAccount
    name: argocd-telegram-bot
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-telegram-bot-reader
  apiGroup: rbac.authorization.k8s.io
