apiVersion: v1
kind: Secret
metadata:
  name: argocd-telegram-bot-secret
  namespace: argocd
  labels:
    app: argocd-telegram-bot
type: Opaque
stringData:
  # Thay bằng Token tạo từ @BotFather trên Telegram
  TELEGRAM_BOT_TOKEN: "-"
